version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URI: "postgresql://myuser:mypassword@db:5432/mydatabase"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db-data:
